embeddings {
  tensor_name: "Store ID:35550"
  metadata_path: "35550/Store ID\\metadata.tsv"
  tensor_path: "35550/Store ID\\tensors.tsv"
}
embeddings {
  tensor_name: "Product ID:35550"
  metadata_path: "35550/Product ID\\metadata.tsv"
  tensor_path: "35550/Product ID\\tensors.tsv"
}
embeddings {
  tensor_name: "Category:35550"
  metadata_path: "35550/Category\\metadata.tsv"
  tensor_path: "35550/Category\\tensors.tsv"
}
embeddings {
  tensor_name: "Region:35550"
  metadata_path: "35550/Region\\metadata.tsv"
  tensor_path: "35550/Region\\tensors.tsv"
}
embeddings {
  tensor_name: "Month:35550"
  metadata_path: "35550/Month\\metadata.tsv"
  tensor_path: "35550/Month\\tensors.tsv"
}
embeddings {
  tensor_name: "DayOfWeek:35550"
  metadata_path: "35550/DayOfWeek\\metadata.tsv"
  tensor_path: "35550/DayOfWeek\\tensors.tsv"
}
embeddings {
  tensor_name: "Seasonality:35550"
  metadata_path: "35550/Seasonality\\metadata.tsv"
  tensor_path: "35550/Seasonality\\tensors.tsv"
}
embeddings {
  tensor_name: "Weather Condition:35550"
  metadata_path: "35550/Weather Condition\\metadata.tsv"
  tensor_path: "35550/Weather Condition\\tensors.tsv"
}
